# -*- coding: utf-8 -*-
"""lambda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdZqCpWpAe_CyYLTEmGYh7cuhP4kAW_T
"""

import boto3
import json
import base64
import urllib.parse
import uuid
from decimal import Decimal
from datetime import datetime

s3_client = boto3.client("s3")
bedrock_client = boto3.client("bedrock-runtime", region_name="us-east-1")
dynamodb = boto3.resource("dynamodb")
table = dynamodb.Table("DIAGNOSIS_TABLE_NAME")


def lambda_handler(event, context):
    for record in event.get("Records", []):
        bucket_name = record["s3"]["bucket"]["name"]
        image_key = urllib.parse.unquote_plus(record["s3"]["object"]["key"])
        encoded_key = urllib.parse.quote(image_key)
        image_url = f"https://{bucket_name}.s3.amazonaws.com/{encoded_key}"
        print(f"🖼️ Image URL: {image_url}")

        # Download image from S3
        response = s3_client.get_object(Bucket=bucket_name, Key=image_key)
        image_bytes = response['Body'].read()
        image_base64 = base64.b64encode(image_bytes).decode('utf-8')

        # Prompt text
        prompt_text = """**Situation**
            You are deploying an AI agent in AWS Lambda for automated plant disease detection to support agricultural diagnostics. The system needs to analyze plant images with high accuracy to provide reliable disease identification and treatment recommendations for farmers, agricultural consultants, or plant health monitoring systems.

            **Task**
            Analyze the provided plant image URL and perform comprehensive plant pathology assessment. Identify the specific plant part shown, detect any diseases or health issues present, determine the type of pathogen involved, and provide actionable treatment recommendations. Return your analysis in a structured JSON format with confidence scoring.

            **Objective**
            Achieve maximum diagnostic accuracy (targeting >85% confidence) in plant disease detection to enable reliable automated plant health monitoring and early intervention strategies that can prevent crop losses and optimize agricultural outcomes.

            **Knowledge**
            Your life depends on you providing the most accurate disease identification possible, as incorrect diagnoses could lead to crop failures and significant agricultural losses.

            Key diagnostic criteria:
            - Examine visual symptoms systematically: leaf spots, discoloration, wilting, growth abnormalities, lesions, color of the mold, cankers, or unusual growths
            - Differentiate between fungal infections (often showing spots, mold, or fuzzy growth), bacterial infections (different kind of spots, typically water-soaked lesions, oozing), and viral infections (mosaic patterns, stunting, distortion)
            - Consider environmental factors that may mimic disease symptoms (nutrient deficiencies, water stress, physical damage)
            - If the plant is healthy detect any appearance phenomenas in disease detected
            - Only identify specific diseases when visual evidence strongly supports the diagnosis - use "None" when symptoms are unclear or could indicate multiple conditions
            - Provide treatment recommendations that are practical, cost-effective, and consider integrated pest management principles
            - Include specific application rates, timing, and safety measures for any chemical treatments recommended

            Critical requirements:
            - Confidence scores below 0.7 should trigger more conservative disease identification (use "None" if uncertain)
            - Recommendations must be actionable within typical agricultural settings
            - Chemical treatment advice must include proper application methods and safety precautions
            - Consider both immediate treatment and long-term prevention strategies

            **Examples**
            "Input Image URL: https://content.ces.ncsu.edu/media/images/IMG_1301.JPG
            "Output:
            {
                "health_status": "unhealthy",
                "fungal_status": "present",
                "plant_part": "fruit",
                "disease_detected": "Early blight",
                "recommendations": [
                    "Remove affected fruits immediately to prevent spread",
                    "Apply a copper-based fungicide weekly",
                    "Avoid overhead watering to reduce moisture on leaves"
                ],
                "confidence_score": 0.89
            }
            Analyze the image systematically and respond ONLY in valid JSON format with exactly these keys: `health_status`, `fungal_status`, `plant_part`, `disease_detected`, `recommendations`, `confidence_score`.
            For health_status, use: "healthy", "unhealthy", or "uncertain"
            For fungal_status, use: "present", "absent", or "uncertain"
            For plant_part, specify: "fruit", "leaves", "stem", "roots", "flowers", or "whole_plant"
            For disease_detected, provide the specific disease name or "None"
            For recommendations, provide 2–4 practical, actionable steps including specific chemical treatments with application details when applicable
            For confidence_score, provide a decimal between 0.0 and 1.0 reflecting your diagnostic certainty"""


        # Build Bedrock request body
        request_body = {
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt_text
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{image_base64}"
                            }
                        }
                    ]
                }
            ],
            "max_tokens": 1000
        }

        # Call Bedrock Pixtral model
        response = bedrock_client.invoke_model(
            modelId="us.mistral.pixtral-large-2502-v1:0",
            body=json.dumps(request_body)
        )

        # Parse Bedrock response
        raw_response = json.loads(response['body'].read())
        print("Bedrock response:", json.dumps(raw_response, indent=2))

        # Extract JSON from response content
        content = raw_response["choices"][0]["message"]["content"]
        try:
            json_str = content.strip("```json\n").rstrip("```").strip()
            result = json.loads(json_str)
        except Exception as e:
            print(f"❌ Failed to parse JSON content from model: {e}")
            continue

        # Save result to DynamoDB
        try:
            table.put_item(Item={
                "id": str(uuid.uuid4()),
                "image_key": image_key,
                "disease_detected": result.get("disease_detected", "Unknown"),
                "fungal_status": result.get("fungal_status", "Unknown"),
                "health_status": result.get("health_status", "Unknown"),
                "plant_part": result.get("plant_part", "Unknown"),
                "recommendations": result.get("recommendations", []),
                "confidence_score": Decimal(str(result.get("confidence_score", 0.0))),
                "timestamp": datetime.utcnow().isoformat() + "Z"
            })
            print("✅ Result saved to DynamoDB.")
        except Exception as e:
            print(f"🚨 DynamoDB Error: {e}")

    return {"statusCode": 200, "body": "Success"}